### ISSUE TITLE
[FEATURE]: send raw comands

### ISSUE THREAD

**Issue by naiz0** [XeroxDev/Loupedeck-plugin-VoiceMeeter#18]
### Consent

- [X] I have searched the existing issues and verified that there is no open issue for the same subject.
- [X] I understand that the Loupedeck VoiceMeeter plugin has NO affiliation with VoiceMeeter.com or VB-Audio

### Feature

Hi Xerox,

maybe you know the Streamdeck Voicemeeter Plugin from the BarRaider Guys:
with the "Advanced Toggle" Button i can send commands directly to VM.

**Sample:** 
Strip[5].B3=1;
and if B3 is already 1, set it to 0.

is it possible to make the same for the Loupdeck?

**Comment by XeroxDev** [comment]
Hey and thank you for opening this feature request. I thought I had already responded, but it seems I didn't :D

Sadly, for now, this isn't possible to add due to missing features in the Loupedeck API. Or at least: I can't make it user friendly.

I won't close this issue, but I'll set it on hold and add it after the features are available.

/label +hold +accepted +blocked

**Comment by XeroxDev** [comment]
Update:

Loupedeck supports now everything needed.

![image](https://github.com/user-attachments/assets/3fb590e9-bb12-4056-92fe-40f8365c8870)
![image](https://github.com/user-attachments/assets/ef16ff8c-3572-44f1-92cb-533c4cc75e10)

I hope this is enough (for the adjustment, buttons will have kinda the same settings)
